
FELICITY_BACKEND = 'felicity.backends.redisd.RedisBackend'

FELICITY_CONFIG = {}

FELICITY_DATABASE_CACHE_BACKEND = None

FELICITY_DATABASE_CACHE_AUTOFILL_TIMEOUT = 60 * 60 * 24

FELICITY_DATABASE_PREFIX = ''

FELICITY_REDIS_PREFIX = 'felicity:'

FELICITY_REDIS_CONNECTION_CLASS = None

FELICITY_REDIS_CONNECTION = {}

FELICITY_SUPERUSER_ONLY = False

FELICITY_MONGO_NAMESPACE = 'default'

FELICITY_MONGO_COLLECTION = 'config'

FELICITY_MONGO_CONNECTION_CLASS = 'default'

FELICITY_MONGO_NAMESPACE = 'default'
